server:
  servlet:
    context-path: '/shiro'

spring:
  application:
    name: 'shiro'
  mvc:
    view:
      # 将模板替换为jsp，默认使用的是thymeleaf
      prefix: '/'
      suffix: '.jsp'
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=utf-8&serverTimezone=Asia/Shanghai'
    username: 'root'
    password: ''

mybatis:
  type-aliases-package: net.ysq.shiro.entity
  mapper-locations: 'classpath:mapper/*.xml'
  configuration:
    # 驼峰命名转换
    map-underscore-to-camel-case: true
    # 增加打印sql语句，一般用于本地开发测试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
